apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: live-express-app
  name: live-express-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      io.kompose.service: live-express-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: live-express-app
    spec:
      containers:
      - image: angagedocker/live-express-prod
        imagePullPolicy: Always
        name: live-express-app
        ports:
          - containerPort: 8081
          - containerPort: 8230
          - containerPort: 8231
        resources: 
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1500Mi                        
        env:
        - name: JAVA_OPTIONS
          value: -Xmx1024m -Xms256m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8230 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8231 -Djava.rmi.server.hostname=localhost
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger,schedule
        - name: LOGGING_LEVEL_ROOT
          value: DEBUG
        - name: LOGGING_LEVEL_COM_ANGAGE_EXPRESS_CLIENT_UAA_UaaFeignClient
          value: DEBUG
        - name: LOGGING_LEVEL_IO_GITHUB_JHIPSTER
          value: DEBUG
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://admin:admin@jhipster-registry:8761/eureka"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://admin:admin@jhipster-registry:8761/config"
#        - name: SPRING_DATA_MONGODB_URI
#          value: "mongodb://angage-user:angage-pabH7hGEGpFPfrtDKDzb85bxL6xHX7PH@10.133.223.111:27017/angage"
#        - name: SPRING_DATA_MONGODB_DATABASE
#          value: angage
#        - name: JHIPSTER_MAIL_BASEURL
#          value: https://angage.live
#        - name: JHIPSTER_MAIL_FROM
#          value: Angage.live <welcome@angage.live>
        - name: JHIPSTER_SLEEP
          value: "10" # gives time for the JHipster Registry to boot before the application
        - name: SPRING_CLOUD_STREAM_BINDERS_RABBITANGAGE_ENVIRONMENT_SPRING_RABBITMQ_HOST
          value: rabbit
        - name: SPRING_RABBITMQ_HOST
          value: rabbit
        - name: APPLICATION_STOMP-HOST
          value: rabbit
        - name: APPLICATION_STOMP-PORT
          value: "61613"
        - name: APPLICATION_STOMP-USER
          value: angage
        - name: APPLICATION_STOMP-PASSWORD
          value: angage
        - name: APPLICATION_STOMP-VHOST
          value: angage
        - name: SPRING_CLOUD_INETUTILS_PREFERRED-NETWORKS
          value: "10.0.1"
        - name: SALESMACHINE_ACTIVATED
          value: "true"
        - name: SALESFORCE_ACTIVATED
          value: "true"
        - name: SALESMACHINE_ACTIVATED
          value: "true"
#        - name: AUDIOWALL_BASE-URL
#          value: https://wall.audio
#        - name: ANTMEDIA_BASE-URL
#          value: https://webcast.angage.com/WebcastApp/
#        - name: ANTMEDIA_WS-URL
#          value: wss://webcast.angage.com/WebcastApp/websocket
#        - name: APPLICATION_AWS_ANGAGE-VIDEO-BUCKET
#          value: angage.webcast
#        - name: ANTMEDIA_AWS-URL
#          value: "https://s3-eu-west-1.amazonaws.com/angage.webcast/"
#        - name: ANTMEDIA_SECRET_KEY
#          value: PbQfmqTiwB5GBjmsPlgcj1TBgmrDhlY1
#        - name:  ANTMEDIA_TOKEN_HASH_SECRET
#          value: fwmZ5omRV9
#        - name: AWS_LAMBDA-ACCESS-CODE
#          value: 93xH8XJKzPCK-cFvD$m!w
#        - name: JHIPSTER_MAIL_FROM
#          value: no_reply@angage.live
#        - name: SPRING_MAIL_HOST
#          value: in-v3.mailjet.com
#        - name: SPRING_MAIL_PORT
#          value: "587"
#        - name: SPRING_MAIL_USERNAME
#          value: 649949bfee3d6f5f076f073fabb32951
#        - name: SPRING_MAIL_PASSWORD
#          value: 6f6080c307978b10a5b41e7e2d310d2b
#        - name: SALESFORCE_OID
#          value: 00D30000000KmWk
        - name: HAZELCAST_INTERFACES
          value: "10.0.7.*"
#        - name: AWS_ANGAGE_VIDEO_BUCKET_REGION
#          value: eu-west-1
#        - name: AWS_ACCESS_KEY_ID
#          value: AKIAUV6NX2KS5TE3NOHG
#        - name: AWS_SECRET_ACCESS_KEY
#          value: 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
#        - name: AWS_IMAGE_BUCKET
#          value: angage-live-images-prod
        - name: APPLICATION_LIVE_STREAM_MP4_ENABLED
          value: "1"
        - name: APPLICATION_WEIGHT_LIMIT
          value: "1000000"
        - name : APPLICATION_WEB_SOCKET_SCHEDULE
          value: "2000"
      imagePullSecrets:
      - name: hub
      restartPolicy: Always
status: {}

