kind: Secret
apiVersion: v1
metadata:
  name: hub
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXNW5ZV2RsWkc5amEyVnlPakl4VUZCeWNrdG5ZakU0VUc5VVNEQT0iCgkJfSwKCQkicmVnaXN0cnkuaHViLmRvY2tlci5jb20iOiB7CgkJCSJhdXRoIjogIllXNW5ZV2RsWkc5amEyVnlPakF4WXpVNE1UWTRMVGhqTXpBdE5EUmpZeTFoTjJNeUxXRTJOemRsTnpnd01tWmlNZz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson