apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: live-management-app
  name: live-management-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      io.kompose.service: live-management-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: live-management-app
    spec:
      containers:
      - image: angagedocker/live-management-prod
        imagePullPolicy: Always
        name: live-management-app
        ports:
          - containerPort: 8082
          - containerPort: 8240
          - containerPort: 8241
        resources: 
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1500Mi                        
        env:
        - name: JAVA_OPTIONS
          value: -Xmx1024m -Xms256m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8240 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8241 -Djava.rmi.server.hostname=localhost 
        - name: SPRING_PROFILES_ACTIVE
          value: dev,swagger,schedule
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://admin:admin@jhipster-registry:8761/eureka"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://admin:admin@jhipster-registry:8761/config"
#        - name: SPRING_DATA_MONGODB_URI
#          value: "mongodb://management-user:management-dpEQQBwcjbtK9sTcyAK6pfJnNAnfahzz@10.133.223.111:27017/management"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: management
#        - name: JHIPSTER_MAIL_BASEURL
#          value: https://angage.live
#        - name: JHIPSTER_MAIL_FROM
#          value: Angage.live <welcome@angage.live>
        - name: JHIPSTER_SLEEP
          value: "10" # gives time for the JHipster Registry to boot before the application
        - name: SPRING_CLOUD_STREAM_BINDERS_RABBITANGAGE_ENVIRONMENT_SPRING_RABBITMQ_HOST
          value: rabbit
        - name: SPRING_RABBITMQ_HOST
          value: rabbit
        - name: APPLICATION_STOMP-HOST
          value: rabbit
        - name: APPLICATION_STOMP-PORT
          value: "61613"
        - name: APPLICATION_STOMP-USER
          value: angage
        - name: APPLICATION_STOMP-PASSWORD
          value: angage
        - name: APPLICATION_STOMP-VHOST
          value: angage
        - name: APPLICATION_ANGAGE-EMAIL
          value: welcome@angage.com           
        - name: SPRING_CLOUD_INETUTILS_PREFERRED-NETWORKS
          value: "10.0.1"
#        - name: SPRING_CLOUD_STREAM_BINDINGS_REQUESTPLAN_GROUP
#          value: grp-management
#        - name: STRIPE_TAXID
#          value: txr_1FyxfzApsu9oShWf5IQCOHUa
#        - name: STRIPE_KEYS_PUBLIC
#          value: pk_live_TnxvRCGBTPGwRSQGGRCzPvGC00njkYp1yg
#        - name: STRIPE_KEYS_SECRET
#          value: sk_live_xz4jMrTvecm0pmnFWv7vT4hw00vNikjtFc
#        - name: JHIPSTER_MAIL_FROM
#          value: no_reply@angage.live
#        - name: SPRING_MAIL_HOST
#          value: in-v3.mailjet.com
#        - name: SPRING_MAIL_PORT
#          value: "587"
#        - name: SPRING_MAIL_USERNAME
#          value: 649949bfee3d6f5f076f073fabb32951
#        - name: SPRING_MAIL_PASSWORD
#          value: 6f6080c307978b10a5b41e7e2d310d2b
#        - name: SALESFORCE_OID
#          value: 00D30000000KmWk
        - name: HAZELCAST_INTERFACES
          value: "10.0.7.*"

      imagePullSecrets:
      - name: hub
      restartPolicy: Always
status: {}

