apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: live-uaa-app
  name: live-uaa-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      io.kompose.service: live-uaa-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: live-uaa-app
    spec:
      containers:
      - image: angagedocker/live-uaa-prod
        imagePullPolicy: Always
        name: live-uaa-app
        ports:
          - containerPort: 9999
          - containerPort: 15700
          - containerPort: 5701
        resources: 
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 1500Mi                        
        env:
        - name: JAVA_OPTIONS
          value: -Xmx1024m -Xms256m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8220 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8221 -Djava.rmi.server.hostname=localhost
        - name: SPRING_PROFILES_ACTIVE
          value: prod,swagger,schedule
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://admin:admin@jhipster-registry:8761/eureka"
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://admin:admin@jhipster-registry:8761/config"
#        - name: SPRING_DATA_MONGODB_URI
#          value: "mongodb://uaa-user:uaa-vyr5Tgma83E8fP8e8uf9v7aebAWSkEHj@10.133.223.111:27017/uaa"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: uaa
#        - name: JHIPSTER_MAIL_BASEURL
#          value: https://angage.live
#        - name: JHIPSTER_MAIL_FROM
#          value: Angage.live <welcome@angage.live>
        - name: JHIPSTER_SLEEP
          value: "10" # gives time for the JHipster Registry to boot before the application
        - name: SPRING_CLOUD_STREAM_BINDERS_RABBITANGAGE_ENVIRONMENT_SPRING_RABBITMQ_HOST
          value: rabbit
        - name: SPRING_RABBITMQ_HOST
          value: rabbit
        - name: APPLICATION_STOMP-HOST
          value: rabbit
        - name: APPLICATION_STOMP-PORT
          value: "61613"
        - name: APPLICATION_STOMP-USER
          value: angage
        - name: APPLICATION_STOMP-PASSWORD
          value: angage
        - name: APPLICATION_STOMP-VHOST
          value: angage
        - name: SPRING_CLOUD_INETUTILS_PREFERRED-NETWORKS
          value: "10.0.1"
        - name: SALESMACHINE_ACTIVATED
          value: "true"
        - name: SALESFORCE_ACTIVATED
          value: "true"
#        - name: JHIPSTER_MAIL_FROM
#          value: no_reply@angage.live
#        - name: SPRING_MAIL_HOST
#          value: in-v3.mailjet.com
#        - name: SPRING_MAIL_PORT
#          value: "587"
#        - name: SPRING_MAIL_USERNAME
#          value: 649949bfee3d6f5f076f073fabb32951
#        - name: SPRING_MAIL_PASSWORD
#          value: 6f6080c307978b10a5b41e7e2d310d2b
#        - name: SALESFORCE_OID
#          value: 00D30000000KmWk
        - name: HAZELCAST_INTERFACES
          value: "10.0.7.*"
#        - name: AWS_ANGAGE_VIDEO_BUCKET_REGION
#          value: eu-west-1
#        - name: AWS_ACCESS_KEY_ID
#          value: AKIAUV6NX2KS5TE3NOHG
#        - name: AWS_SECRET_ACCESS_KEY
#          value: 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
#        - name: AWS_IMAGE_BUCKET
#          value: angage-live-images-prod
        - name: APPLICATION_GOOGLE_RECAPTCHA_KEY_SITE
          value: 6Lc1gI4aAAAAACd23XMzQv5bv4NbZ_7stUjDqe4i
        - name: APPLICATION_GOOGLE_RECAPTCHA_KEY_SECRET
          value: 6Lc1gI4aAAAAAKbNNkV9F90RM_lksFo51z6jMv7P
        - name: APPLICATION_GOOGLE_RECAPTCHA_KEY_THRESHOLD
          value: "0.2"
        - name: APPLICATION_GOOGLE_RECAPTCHA_ENABLED
          value: "true"

      imagePullSecrets:
      - name: hub
      restartPolicy: Always
status: {}

